### ISSUE TITLE
Clarification on JSON input format with Hugging Face visual-question-answering module

### ISSUE THREAD

**Issue by chienyutseng** [omnitool-ai/omnitool#2]
Hello,

I am utilizing the Hugging Face visual question-answering interface component 'huggingface.hf_visual_question_answering' and I suspect there might be an issue with the JSON input format, which could be leading to an error. I am seeking clarification on the proper JSON input structure required by this component.

Could the team provide guidance or examples of the correct JSON input format?

### Error Encountered:
Subsequent to input submission of the image as follow:
`{"image":"http://images.cocodataset.org/val2017/000000039769.jpg"}`,

and return with the error message:
```
Error! A block returned an error with componentKey: 'huggingface.hf_visual_question_answering' Details: 'Cannot read properties of undefined (reading 'ticket')'.
```

Screenshots/Logs:
![image](https://github.com/omnitool-ai/omnitool/assets/124143619/21d14450-b36f-4abb-bb05-064c41960f66)

I think any assistance to confirm the correct JSON input format would be appreciated!

Thank you.

**Comment by manu-sapiens** [comment]
Let me take a look!

**Comment by manu-sapiens** [comment]
ok, three issues actually: 

- the code was not reading the passed image properly (fixed)
- the image was not converted to a Blob as expected (fixed)
- the default model used when no model is passed as a parameter seems to have issues outside of our control. Using a specific model like dandelin/vilt-b32-finetuned-vqa resolves this problem.
The fixes will be live in 1.0.3. Meanwhile, using a llava model (for example, on Replicate) will give you much of the same functionality.
I'll close this issue once 1.0.3 is live.

**Comment by manu-sapiens** [comment]
1.0.3 is live so this fix should be too!

**Comment by chienyutseng** [comment]
thanks for the update, i've been updated to the newest version 1.0.3.
However , I'm still struggling with the json format of the input json, which the snapshot below still not working.
Could you provide guidance or examples of the correct JSON input format?

<img width="563" alt="image" src="https://github.com/omnitool-ai/omnitool/assets/124143619/b905c64b-ef22-41ba-920c-9957d671b798">
